sudo: required

language: node_js

node_js:
    - 0.10

services:
    - docker

before_install:
    - docker build -t jekkos/opensourcepos .
    - docker run -d -p 127.0.0.1:80:80 jekkos/opensourcepos /bin/sh -c "cd /app; npm install"
    - docker ps -a

script:
    - grunt mochaWebdriver:test
